/*
INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'Admin', 'Istrator', '$2a$10$n/r9HurPFd9JBE1B6cJIG.6UjfRKgjl23l8NI.Kn/1shetD1QaRJG', 'admin', 'admin', '2016-01-01 00:00:00')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('admin', 'ADMIN')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('admin', 'STUDENT')
INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'Susi', 'Kaufgern', '$2a$10$n/r9HurPFd9JBE1B6cJIG.6UjfRKgjl23l8NI.Kn/1shetD1QaRJG', 'user1', 'admin', '2016-01-01 00:00:00')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('user1', 'PSLEADER')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('user1', 'STUDENT')
INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'Max', 'Mustermann', '$2a$10$n/r9HurPFd9JBE1B6cJIG.6UjfRKgjl23l8NI.Kn/1shetD1QaRJG', 'user2', 'admin', '2016-01-01 00:00:00')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('user2', 'STUDENT')
INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'Adrian', 'Natter', '$2a$10$iYl7Qas3A4oGgM1TmqhXVeUUYcCH8veb3KSiCtVdQn8YIfeySsWeu', 'user3', 'admin', '2016-01-01 00:00:00')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('user3', 'ADMIN')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('user3', 'PSLEADER')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('user3', 'STUDENT')
*/

/* TEST USER ANDRE TO TEST INDIVIDUAL VISIBILITIES

INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'test', 'admin', '$2a$10$n/r9HurPFd9JBE1B6cJIG.6UjfRKgjl23l8NI.Kn/1shetD1QaRJG', 'testAdmin', 'admin', '2016-01-01 00:00:00')

INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('testAdmin', 'ADMIN')


INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'test', 'PSLeader', '$2a$10$n/r9HurPFd9JBE1B6cJIG.6UjfRKgjl23l8NI.Kn/1shetD1QaRJG', 'testPSLeader', 'admin', '2016-01-01 00:00:00')

INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('testPSLeader', 'PSLEADER')


INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'test', 'Student', '$2a$10$n/r9HurPFd9JBE1B6cJIG.6UjfRKgjl23l8NI.Kn/1shetD1QaRJG', 'testStudent', 'admin', '2016-01-01 00:00:00')

INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('testStudent', 'STUDENT')

*/

INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'Admin', 'Istrator', '$2a$10$n/r9HurPFd9JBE1B6cJIG.6UjfRKgjl23l8NI.Kn/1shetD1QaRJG', 'admin', 'admin', '2017-01-01 00:00:00')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('admin', 'ADMIN')