INSERT INTO USER (INACTIVE, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE, EMAIL, ADDRESS, PHONE) VALUES(FALSE, TRUE, 'Admin', 'Istrator', 'passwd', 'admin', 'admin', '2016-01-01 00:00:00', 'hallo@welt.at', 'Anichstraße 19', '0660/1234455')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('admin', 'ADMIN')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('admin', 'EMPLOYEE')

